services:
  games-brodin:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_NTFY_SERVER_URL=${VITE_NTFY_SERVER_URL}
        - VITE_DEBUG=${VITE_DEBUG}
    ports:
      - "8081:80"
    restart: unless-stopped
